### ISSUE TITLE
xclip/xsel on Ubuntu

### ISSUE THREAD

**Issue by dmi3kno** [yonicd/slackreprex#1]
When using `slackreprex` for the first time on Ubuntu, the following message was returned:
```r
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
```
Since it seems you already know user is on Linux, you could offer helpful guidance, like Jeroen often does:
```r
#> Clipboard on X11 requires 'xclip' (recommended) or 'xsel'. On Ubuntu, open the terminal and type:
#>  sudo apt-get update -y 
#>  sudo apt-get install -y xclip 
```

**Comment by yonicd** [comment]
sure i can add that. 

i think that is a reprex problem though since the function calls reprex internally.

**Comment by dmi3kno** [comment]
Fair enough. Closing it, and will add it there.
