### ISSUE TITLE
Large reprex fail silently

### ISSUE THREAD

**Issue by TylerGrantSmith** [yonicd/slackreprex#3]
I attempted to use `slack_reprex` and the result apparently exceeded the character limit.  The error is not caught because `validate_response` is only checking for http status errors, but the slack API returns a valid response with the error coded in JSON.  Here is the output of `httr::content(res)`

```
Browse[11]> httr::content(res)
$ok
[1] FALSE

$error
[1] "invalid_blocks"

$response_metadata
$response_metadata$messages
$response_metadata$messages[[1]]
[1] "[ERROR] failed to match all allowed schemas [json-pointer:/blocks/0/text]"

$response_metadata$messages[[2]]
[1] "[ERROR] must be less than 3001 characters [json-pointer:/blocks/0/text/text]"
```

I don't know of a good way to give a reprex for this because of the key requirements, but you should be able to just reprex `"strrep("a", 3001)"`

**Comment by yonicd** [comment]
Blocks can be split into pieces by character limits. 

Thanks for catching this.

**Comment by yonicd** [comment]
fixed https://github.com/yonicd/slackreprex/commit/41273978c4a8e21cccb49f557e19f92c0bdc53e4
